export const keyboardLayout = [
  ['Backquote'],
  ['Digit1'],
  ['Digit2'],
  ['Digit3'],
  ['Digit4'],
  ['Digit5'],
  ['Digit6'],
  ['Digit7'],
  ['Digit8'],
  ['Digit9'],
  ['Digit0'],
  ['Minus'],
  ['Equal'],
  ['Backspace'],
  ['Delete'],
  ['Tab'],
  ['KeyQ'],
  ['KeyW'],
  ['KeyE'],
  ['KeyR'],
  ['KeyT'],
  ['KeyY'],
  ['KeyU'],
  ['KeyI'],
  ['KeyO'],
  ['KeyP'],
  ['BracketLeft'],
  ['BracketRight'],
  ['Backslash'],
  ['KeyA'],
  ['KeyS'],
  ['KeyD'],
  ['KeyF'],
  ['KeyG'],
  ['KeyH'],
  ['KeyJ'],
  ['KeyK'],
  ['KeyL'],
  ['Semicolon'],
  ['Quote'],
  ['Enter'],
  ['ShiftLeft'],
  ['KeyZ'],
  ['KeyX'],
  ['KeyC'],
  ['KeyV'],
  ['KeyB'],
  ['KeyN'],
  ['KeyM'],
  ['Comma'],
  ['Period'],
  ['Slash'],
  ['ShiftRight'],
  ['ArrowUp'],
  ['ControlLeft'],
  ['MetaLeft'],
  ['AltLeft'],
  ['Space'],
  ['AltRight'],
  ['MetaRight'],
  ['ControlRight'],
  ['ArrowLeft'],
  ['ArrowDown'],
  ['ArrowRight'],
];

export const keys = {
  functional: {
    Escape: 'Escape',
    Tab: 'tab',
    ShiftLeft: 'shift',
    ShiftRight: 'shift',
    ControlLeft: 'ctrl',
    MetaLeft: 'win',
    AltLeft: 'alt',
    Space: 'Space',
    AltRight: 'alt',
    MetaRight: 'win',
    ControlRight: 'ctrl',
    Pause: 'pause',
    Delete: 'del',
    Backspace: '⟵',
    ArrowUp: '˄',
    ArrowLeft: '˂',
    ArrowRight: '˃',
    ArrowDown: '˅',
    Enter: 'Enter',
  },
  symbols: {
    ru: {
      Backquote: { shift: 'Ё', main: 'ё' },
      Digit1: { shift: '!', main: '1' },
      Digit2: { shift: '"', main: '2' },
      Digit3: { shift: '№', main: '3' },
      Digit4: { shift: ';', main: '4' },
      Digit5: { shift: '%', main: '5' },
      Digit6: { shift: ':', main: '6' },
      Digit7: { shift: '?', main: '7' },
      Digit8: { shift: '*', main: '8' },
      Digit9: { shift: '(', main: '9' },
      Digit0: { shift: ')', main: '0' },
      Minus: { shift: '_', main: '-' },
      Equal: { shift: '+', main: '=' },
      Backslash: { shift: '/', main: '\\' },
      KeyQ: { shift: 'Й', main: 'й' },
      KeyW: { shift: 'Ц', main: 'ц' },
      KeyE: { shift: 'У', main: 'у' },
      KeyR: { shift: 'К', main: 'к' },
      KeyT: { shift: 'Е', main: 'е' },
      KeyY: { shift: 'Н', main: 'н' },
      KeyU: { shift: 'Г', main: 'г' },
      KeyI: { shift: 'Ш', main: 'ш' },
      KeyO: { shift: 'Щ', main: 'щ' },
      KeyP: { shift: 'З', main: 'з' },
      BracketLeft: { shift: 'Х', main: 'х' },
      BracketRight: { shift: 'Ъ', main: 'ъ' },
      KeyA: { shift: 'Ф', main: 'ф' },
      KeyS: { shift: 'Ы', main: 'ы' },
      KeyD: { shift: 'В', main: 'в' },
      KeyF: { shift: 'А', main: 'а' },
      KeyG: { shift: 'П', main: 'п' },
      KeyH: { shift: 'Р', main: 'р' },
      KeyJ: { shift: 'О', main: 'о' },
      KeyK: { shift: 'Л', main: 'л' },
      KeyL: { shift: 'Д', main: 'д' },
      Semicolon: { shift: 'Ж', main: 'ж' },
      Quote: { shift: 'Э', main: 'э' },
      KeyZ: { shift: 'Я', main: 'я' },
      KeyX: { shift: 'Ч', main: 'ч' },
      KeyC: { shift: 'С', main: 'с' },
      KeyV: { shift: 'М', main: 'м' },
      KeyB: { shift: 'И', main: 'и' },
      KeyN: { shift: 'Т', main: 'т' },
      KeyM: { shift: 'Ь', main: 'ь' },
      Comma: { shift: 'Б', main: 'б' },
      Period: { shift: 'Ю', main: 'ю' },
      Slash: { shift: ',', main: '.' },
    },
    en: {
      Digit1: { shift: '!', main: '1' },
      Digit2: { shift: '@', main: '2' },
      Digit3: { shift: '#', main: '3' },
      Digit4: { shift: '$', main: '4' },
      Digit5: { shift: '%', main: '5' },
      Digit6: { shift: '^', main: '6' },
      Digit7: { shift: '&', main: '7' },
      Digit8: { shift: '*', main: '8' },
      Digit9: { shift: '(', main: '9' },
      Digit0: { shift: ')', main: '0' },
      Minus: { shift: '_', main: '-' },
      Equal: { shift: '+', main: '=' },
      Backslash: { shift: '|', main: '\\' },
      KeyQ: { shift: 'Q', main: 'q' },
      KeyW: { shift: 'W', main: 'w' },
      KeyE: { shift: 'E', main: 'e' },
      KeyR: { shift: 'R', main: 'r' },
      KeyT: { shift: 'T', main: 't' },
      KeyY: { shift: 'Y', main: 'y' },
      KeyU: { shift: 'U', main: 'u' },
      KeyI: { shift: 'I', main: 'i' },
      KeyO: { shift: 'O', main: 'o' },
      KeyP: { shift: 'P', main: 'p' },
      BracketLeft: { shift: '{', main: '[' },
      BracketRight: { shift: '}', main: ']' },
      KeyA: { shift: 'A', main: 'a' },
      KeyS: { shift: 'S', main: 's' },
      KeyD: { shift: 'D', main: 'd' },
      KeyF: { shift: 'F', main: 'f' },
      KeyG: { shift: 'G', main: 'g' },
      KeyH: { shift: 'H', main: 'h' },
      KeyJ: { shift: 'J', main: 'j' },
      KeyK: { shift: 'K', main: 'k' },
      KeyL: { shift: 'L', main: 'l' },
      Semicolon: { shift: ':', main: ';' },
      Quote: { shift: '"', main: "'" },
      KeyZ: { shift: 'Z', main: 'z' },
      KeyX: { shift: 'X', main: 'x' },
      KeyC: { shift: 'C', main: 'c' },
      KeyV: { shift: 'V', main: 'v' },
      KeyB: { shift: 'B', main: 'b' },
      KeyN: { shift: 'N', main: 'n' },
      KeyM: { shift: 'M', main: 'm' },
      Comma: { shift: '<', main: ',' },
      Period: { shift: '>', main: '.' },
      Slash: { shift: '?', main: '/' },
      Backquote: { shift: '~', main: '`' },
    },
  },
};

export const laguages = ['en', 'ru'];
